@extends('layouts.app')
@section('title', 'ចុះឈ្មោះសិស្ស')
@section('page-title', 'ចុះឈ្មោះសិស្ស')
@section('content')
@if($errors->any())
	<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<div class="card mx-auto" style="max-width:820px"><div class="card-header"><h5 class="mb-0"><i class="fas fa-user-check me-2"></i>ចុះឈ្មោះសិស្ស</h5></div><div class="card-body"><form method="POST" action="{{ route('enrollments.store') }}">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">សិស្ស</label><select name="student_id" class="form-select" required><option value="">-- ជ្រើសរើសសិស្ស --</option>@foreach($students as $student)<option value="{{ $student->id }}" {{ old('student_id', $selectedStudentId) == $student->id ? 'selected' : '' }}>{{ $student->code }} - {{ $student->name_kh }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">ឆ្នាំសិក្សា</label><select name="academic_year_id" class="form-select" required><option value="">-- ជ្រើសរើស --</option>@foreach($academicYears as $year)<option value="{{ $year->id }}">{{ $year->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">កម្រិតថ្នាក់</label><select name="grade_id" class="form-select" required><option value="">-- ជ្រើសរើស --</option>@foreach($grades as $grade)<option value="{{ $grade->id }}">{{ $grade->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">ក្រុម / ថ្នាក់រៀន</label><select name="class_id" class="form-select" required><option value="">-- ជ្រើសរើស --</option>@foreach($classes as $schoolClass)<option value="{{ $schoolClass->id }}">{{ $schoolClass->name }} - {{ $schoolClass->grade?->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">ថ្ងៃចុះឈ្មោះ</label><input type="date" name="enrollment_date" class="form-control" value="{{ now()->format('Y-m-d') }}" required></div><div class="col-md-6"><label class="form-label">សភាព</label><select name="status" class="form-select" required><option value="pending">កំពុងរង់ចាំ</option><option value="active">សកម្ម</option><option value="completed">បានបញ្ចប់</option></select></div></div><div class="text-end mt-4"><a href="{{ route('enrollments.index') }}" class="btn btn-outline-secondary">បោះបង់</a> <button class="btn btn-primary" type="submit">រក្សាទុក</button> <button class="btn btn-success" type="submit" name="save_and_pay" value="1">រក្សាទុក & ទូរទឹកប្រាក់</button></div></form></div></div>
@endsection
